### ISSUE TITLE
how I can see the output of the proposed tool?

### ISSUE THREAD

**Issue by alaalial** [typegen4py/typegen4py#1]
Hi,
First thanks for building this tool, 
When I ran the tool 
 **python run.py gen  C:\Users\00\Desktop\l\typegen4py-main\top-10\top-10\Numpy'**
I got the following output:
**Pytype only: 0, identical: 0, non-identical: 0, common 0**

what does this output mean, and this Pytype, what is the output of the tool typegen4py? where I can see its output?

**Comment by Jarvx** [comment]
The given parameter should be *\top-10\Numpy\tmp.
Please use the dataset I provided.  The script will automatically locate the entry point. I have made one example in README.
I also changed the output format a bit. 
Thank you very much for raising this issue.

Please feel free to reopen!
